スッキリわかるjava入門 Ex4~5
alex-okimai/Mission-1 pull request #10
Opened 2020-07-08 12:46 UTC by WJM99-JMOK

2020-07-09 13:01 UTC, okimai requested changes
修正お願いします。

2020-07-09 13:01 UTC, okimai commented on スッキリわかるjava入門/Ex4_2.java
> +			System.out.println(moneyList[i] + ",");
你这里这么写的话，会连带逗号输出这三行。
121902,
8302,
55100,
我觉得你是不是想输出下面的字符串?
121902, 8302, 55100

2020-07-09 13:01 UTC, okimai commented on スッキリわかるjava入門/Ex5_2.java
> +		System.out.println(text + "メールの本文");
14、15行目がおかしい。
Ex5_3も修正してください。

2020-07-09 13:01 UTC, okimai commented on スッキリわかるjava入門/Ex5_3.java
> +		System.out.println(text + "メールの本文");
ここも修正してください。

2020-07-14 13:09 UTC, WJM99-JMOK commented on スッキリわかるjava入門/Ex4_2.java
> +			System.out.println(moneyList[i] + ",");
格式没有特定要求，只要可以依次展现数列里的元素即可

2020-07-19 01:57 UTC, okimai commented on スッキリわかるjava入門/Ex4_2.java
> +			System.out.println(moneyList[i] + ",");
見逃してやろう。

2020-07-19 02:05 UTC, okimai commented on スッキリわかるjava入門/Ex5_3.java
> +		System.out.println(address + "メールのタイトル");
@WJM99-JMOK 
不好意思，之前看漏了。
你这里12行，13行的变数写反了。
话说你做完题，要认真点动作确认才行，不要以为有个人在看你的代码你就不细心检查，不然以后工作会很苦逼。

2020-07-19 02:08 UTC, okimai commented
@WJM99-JMOK 
顺便一提，实际开发代码的时候，像Ex5_3，你建了两个方法，但是里面的处理是大部分一样的，你可以运用重构，改成以下的形式。
这样的话写出来的代码可维护，出bug的几率也少。
``` java
	public static void email(String title,String address,String text){
		System.out.println(address + "に、以下のメールを送信しました。");
		System.out.println(title != null ? title + "メールのタイトル" : "件名：無題" );
		System.out.println(text + "メールの本文");
	}

	public static void email(String address,String text){
		email(null, address, text);
	}
```

2020-08-15 03:27 UTC, okimai approved these changes

2020-08-15 03:27 UTC, merged